import { memo } from 'react';

/**
 * Collapsible panel exposing the SQL queries generated by the Analytics Engine.
 *
 * Collapsed by default so that non-technical users are not overwhelmed.
 * Each query shows its step number, a natural-language description, and
 * the raw SQL in a monospaced code block.
 *
 * memo'd because generatedQueries is stable after the API response is stored.
 *
 * @param {{ generatedQueries: import('../../types/apiSchemas').GeneratedQuery[] }} props
 */
const SqlViewer = memo(({ generatedQueries }) => (
  <details
    style={{
      backgroundColor: '#0B1120',
      border: '1px solid var(--border)',
      borderRadius: 'var(--radius-md)',
      padding: '0.75rem 1.25rem',
    }}
  >
    <summary
      style={{
        cursor: 'pointer',
        fontWeight: 500,
        fontSize: '0.85rem',
        color: 'var(--text-secondary)',
        outline: 'none',
      }}
    >
      View Generated SQL Queries
    </summary>

    <div
      style={{ marginTop: '1.25rem', display: 'flex', flexDirection: 'column', gap: '1.25rem' }}
    >
      {generatedQueries.map((query, index) => (
        <div
          key={index}
          style={{
            borderBottom:
              index !== generatedQueries.length - 1
                ? '1px solid rgba(255,255,255,0.05)'
                : 'none',
            paddingBottom: index !== generatedQueries.length - 1 ? '1.25rem' : '0',
          }}
        >
          <div
            style={{
              fontSize: '0.8rem',
              color: 'var(--text-secondary)',
              marginBottom: '0.5rem',
              fontWeight: 500,
            }}
          >
            Step {query.step_id}: {query.description}
          </div>
          <pre
            style={{
              margin: 0,
              padding: '1rem',
              backgroundColor: 'rgba(0,0,0,0.3)',
              borderRadius: '6px',
              border: '1px solid rgba(255,255,255,0.05)',
              overflowX: 'auto',
            }}
          >
            <code
              style={{
                fontSize: '0.8rem',
                color: 'var(--success)',
                fontFamily: '"Fira Code", monospace',
              }}
            >
              {query.sql}
            </code>
          </pre>
        </div>
      ))}
    </div>
  </details>
));

SqlViewer.displayName = 'SqlViewer';
export default SqlViewer;
